
import type { Region } from './types';

export const UI_TEXTS = {
  ar: {
    title: "بوصلة الدواء",
    searchPlaceholder: "ابحث بالاسم التجاري، المادة الفعالة، أو الفئة...",
    searchButton: "بحث",
    region: "المنطقة:",
    language: "اللغة:",
    loading: "جاري جلب البيانات...",
    error: "حدث خطأ. الرجاء المحاولة مرة أخرى.",
    noResults: "لا توجد نتائج. جرب البحث عن دواء آخر.",
    initialMessage: "ابحث عن دواء للحصول على معلومات مفصلة.",
    disclaimer: "المعلومات تعليمية ولا تُعدّ نصيحة طبية. راجع طبيبك أو الصيدلي قبل الاستخدام.",
    notMedicalAdvice: "ليست بديلاً عن الطبيب",
    brandNames: "الأسماء التجارية",
    drugClass: "الفئة الدوائية",
    mechanism: "آلية العمل",
    indications: "الاستطبابات (الاستخدامات)",
    dosingAdult: "الجرعات للبالغين",
    dosingPediatric: "الجرعات للأطفال",
    contraindications: "موانع الاستعمال",
    warnings: "تحذيرات واحتياطات",
    adverseEffects: "الآثار الجانبية",
    common: "شائعة",
    serious: "خطيرة",
    interactions: "التداخلات الدوائية",
    severe: "شديدة",
    moderate: "متوسطة",
    minor: "طفيفة",
    food: "الطعام",
    alcohol: "الكحول",
    pregnancy: "الحمل والرضاعة",
    renalHepatic: "التعديل الكلوي/الكبدي",
    alternatives: "البدائل",
    genericEquivalents: "المكافئ الجنيس",
    therapeuticAlternatives: "البدائل العلاجية",
    references: "المصادر",
    quickWarnings: "تحذيرات سريعة",
    boxedWarning: "تحذير الصندوق الأسود",
    identifiers: "المعرفات",
  },
  en: {
    title: "Drug Compass",
    searchPlaceholder: "Search by brand, generic name, or class...",
    searchButton: "Search",
    region: "Region:",
    language: "Language:",
    loading: "Fetching data...",
    error: "An error occurred. Please try again.",
    noResults: "No results found. Try searching for another drug.",
    initialMessage: "Search for a drug to get detailed information.",
    disclaimer: "This information is for educational purposes and is not medical advice. Consult your doctor or pharmacist before use.",
    notMedicalAdvice: "Not a substitute for a doctor",
    brandNames: "Brand Names",
    drugClass: "Drug Class",
    mechanism: "Mechanism of Action",
    indications: "Indications",
    dosingAdult: "Adult Dosing",
    dosingPediatric: "Pediatric Dosing",
    contraindications: "Contraindications",
    warnings: "Warnings & Precautions",
    adverseEffects: "Adverse Effects",
    common: "Common",
    serious: "Serious",
    interactions: "Drug Interactions",
    severe: "Severe",
    moderate: "Moderate",
    minor: "Minor",
    food: "Food",
    alcohol: "Alcohol",
    pregnancy: "Pregnancy & Lactation",
    renalHepatic: "Renal/Hepatic Adjustment",
    alternatives: "Alternatives",
    genericEquivalents: "Generic Equivalents",
    therapeuticAlternatives: "Therapeutic Alternatives",
    references: "References",
    quickWarnings: "Quick Warnings",
    boxedWarning: "Boxed Warning",
    identifiers: "Identifiers",
  }
};

export const REGIONS: { value: Region; label: string }[] = [
    { value: "global" as Region, label: "Global" },
    { value: "US" as Region, label: "USA (FDA)" },
    { value: "EU" as Region, label: "EU (EMA)" },
    { value: "UK" as Region, label: "UK (NHS)" },
    { value: "SA" as Region, label: "Saudi Arabia (SFDA)" },
];

export const EXAMPLE_DRUGS = {
    ar: ["باراسيتامول", "أيبوبروفين", "أموكسيسيلين", "ميتفورمين", "أوميبرازول"],
    en: ["Paracetamol", "Ibuprofen", "Amoxicillin", "Metformin", "Omeprazole"],
};
